# Copyright 2023–2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CLI utility for running inference on a single/multi stream(s)."""

import os
import socket
import time
from typing import Sequence, Any
import numpy as np
import jax
import jax.numpy as jnp

from absl import app

from maxtext.configs import pyconfig
from maxtext.common import profiler
from maxtext.common.gcloud_stub import jetstream, is_decoupled
from maxtext.inference.maxengine import maxengine
from maxtext.inference.maxengine.maxengine import ExistingPrefix
from maxtext.multimodal import processor as mm_processor
from maxtext.multimodal import utils as mm_utils
from maxtext.utils import max_utils

_config_lib, engine_api, _token_utils, _tokenizer_api, _token_params_ns = jetstream()
# Placeholder: internal

# Number of text sequences to process in a single batch.
_NUM_STREAMS = 1


def _batch_first_result_token(first_tokens: list[Any], batch_size: int):
  """Batches together a list of first result tokens from prefill calls.

  This is needed because prefill currently returns the first token as a batch of size 1
  to optimize latency to first token without padding to the configured batch size, while
  generate returns a batch of configured size. This function batches a list of
  such single-element first tokens into one batch to simulate the normal processing
  that first tokens are generated by generate.

  Args:
    first_tokens: A list of `ResultTokens` representing first token returned by `prefill`
    batch_size: The target batch size to pad to. This should be from the config.
  Return:
    A `ResultTokens` with all first tokens batched as if they are produced by a single
    `generate` step.
  """
  data = jnp.vstack([first_token.data for first_token in first_tokens])

  def _pad_to_batch_size(data: jax.Array, batch_size: int):
    pad_width = [(0, batch_size - data.shape[0]), (0, 0)]
    data = jnp.pad(data, pad_width, mode="constant", constant_values=0)
    return data

  result_tokens = engine_api.ResultTokens(
      data=_pad_to_batch_size(data, batch_size),
      tokens_idx=(0, 1),
      valid_idx=(1, 2),
      length_idx=(2, 3),
      samples_per_slot=1,
  )

  def _all_equals(elements: Sequence[jax.Array], target: jax.Array):
    """Checks if each element equals the given target."""
    stacked = jnp.stack(elements)
    row_comparisons = stacked == target
    return jnp.all(row_comparisons)

  # `tokens_idx`, `valid_idx`, `length_idx` and `samples_per_slot` are hardcoded
  # and should be the same for all first tokens returned from prefill.
  assert _all_equals([jnp.array(t.tokens_idx) for t in first_tokens], jnp.array(result_tokens.tokens_idx))
  assert _all_equals([jnp.array(t.valid_idx) for t in first_tokens], jnp.array(result_tokens.valid_idx))
  assert _all_equals([jnp.array(t.length_idx) for t in first_tokens], jnp.array(result_tokens.length_idx))
  assert _all_equals([jnp.array(t.samples_per_slot) for t in first_tokens], jnp.array(result_tokens.samples_per_slot))

  return result_tokens


def _probe_hbm(label: str, detail: bool = False) -> None:
  """Print per-device HBM memory stats for diagnostics. No logic change."""
  host = socket.gethostname()
  for d in jax.local_devices():
    try:
      stats = d.memory_stats()
      used_gb  = stats.get("bytes_in_use",      0) / 2**30
      limit_gb = stats.get("bytes_limit",        0) / 2**30
      peak_gb  = stats.get("peak_bytes_in_use",  0) / 2**30
      print(
          f"[HBM] {label:<36s} host={host} dev={d.id}"
          f" used={used_gb:.2f}GB peak={peak_gb:.2f}GB limit={limit_gb:.2f}GB",
          flush=True,
      )
    except Exception as e:  # pylint: disable=broad-except
      print(f"[HBM] {label:<36s} host={host} dev={d.id} memory_stats N/A: {e}", flush=True)
    if detail:
      _probe_hbm_arrays(label, d, host)


def _probe_hbm_arrays(label: str, d, host: str) -> None:
  """Enumerate live JAX arrays on device d via addressable_shards, grouped by dtype."""
  from collections import defaultdict  # pylint: disable=import-outside-toplevel
  dtype_count: dict[str, int] = defaultdict(int)
  dtype_bytes: dict[str, int] = defaultdict(int)
  n_arrays = 0
  try:
    all_live = jax.live_arrays()
    for arr in all_live:
      try:
        # addressable_shards gives the actual physical shard on each local device.
        # Works for both sharded and replicated global arrays.
        for shard in arr.addressable_shards:
          if shard.device == d:
            n_arrays += 1
            nbytes = int(shard.data.size) * arr.dtype.itemsize
            dtype_bytes[str(arr.dtype)] += nbytes
            dtype_count[str(arr.dtype)] += 1
      except Exception:  # pylint: disable=broad-except
        pass
    total_live = sum(dtype_bytes.values())
    print(
        f"[HBM-DETAIL] {label:<36s} host={host} dev={d.id}"
        f" shards={n_arrays} total={total_live / 2**30:.3f}GB",
        flush=True,
    )
    for dtype_name, nbytes in sorted(dtype_bytes.items(), key=lambda x: -x[1]):
      pct = 100.0 * nbytes / total_live if total_live else 0.0
      print(
          f"[HBM-DETAIL]   {dtype_name:22s} {nbytes / 2**30:7.3f}GB"
          f"  n={dtype_count[dtype_name]:5d}  ({pct:.1f}%)",
          flush=True,
      )
  except Exception as e:  # pylint: disable=broad-except
    print(f"[HBM-DETAIL] {label:<36s} host={host} dev={d.id} failed: {type(e).__name__}: {e}", flush=True)


def main(argv: Sequence[str]) -> None:
  jax.config.update("jax_default_prng_impl", "unsafe_rbg")
  os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"

  config = pyconfig.initialize(argv)
  _validate_config(config)
  jax.config.update("jax_use_shardy_partitioner", config.shardy)
  max_utils.print_system_information()
  _probe_hbm("init", detail=True)

  engine = maxengine.MaxEngine(config)
  rng = jax.random.PRNGKey(1234)
  rng, rng_load_params = jax.random.split(rng)
  _t_load = time.perf_counter()
  params = engine.load_params(rng_load_params)
  _probe_hbm("after_load_params", detail=True)
  print(f"[TIME] load_params                       host={socket.gethostname()} elapsed={time.perf_counter()-_t_load:.1f}s", flush=True)
  prof = profiler.Profiler(config)

  text = config.prompt
  prefill_length = config.max_prefill_predict_length
  processor_outputs = mm_utils.PreprocessorOutput()
  if config.use_multimodal:
    processor_outputs = mm_processor.preprocess_mm_data(config)
    image_offsets = mm_processor.get_image_offsets(config=config, processor_output=processor_outputs)

    prefill_length -= image_offsets
    text = mm_processor.reformat_prompt(
        prompt=config.prompt,
        image_placeholder=config.image_placeholder,
        video_placeholder=config.video_placeholder,
        model_name=config.model_name,
        num_images=processor_outputs.num_images,
        num_videos=getattr(processor_outputs, 'num_videos', 0),
    )

  metadata = engine.get_tokenizer()
  tokenizer_model = engine.build_tokenizer(metadata)
  token_params_is_stub = getattr(_token_params_ns, "_IS_STUB", False)
  engine_api_is_stub = getattr(engine_api, "_IS_STUB", False)
  if is_decoupled() and (token_params_is_stub or engine_api_is_stub):
    raise RuntimeError(
        "JetStream disabled by DECOUPLE_GCLOUD=TRUE or stubbed; decode requires the JetStream tokenizer. "
        "Unset DECOUPLE_GCLOUD or install JetStream to run decode."
    )

  try:
    # TODO: update jetstream.engine.tokenizer_api.Tokenizer to maintain tokenizer state.
    has_chat_template = getattr(tokenizer_model.tokenizer, "chat_template", False)  # pytype: disable=attribute-error
  except AttributeError as _:
    has_chat_template = False
  if config.use_chat_template and has_chat_template:
    messages = [{"role": "user", "content": text}]
    # enable_thinking=True activates the Qwen3/MiMo thinking-model chat
    # template.  For MiMo-V2-Flash the template still only emits the bare
    # <|im_start|>assistant\n generation prefix; the model does NOT reliably
    # self-start <think> from that prefix.  Manually append <think>\n so the
    # model is already inside a thinking block and must generate its reasoning
    # chain before answering.  Without this the model never produces
    # <|im_end|> (EOS) and the output degenerates.
    text = tokenizer_model.tokenizer.apply_chat_template(  # pytype: disable=attribute-error
        messages, tokenize=False, add_generation_prompt=True, enable_thinking=True
    )
    if not text.endswith("<think>") and not text.endswith("<think>\n"):
      text = text + "<think>\n"
  tokens, true_length = tokenizer_model.encode(text, is_bos=not has_chat_template, prefill_lengths=[prefill_length])

  position_ids = None
  mrope_position_deltas = None

  if config.use_multimodal:
    tokens = mm_processor.prepare_text_for_image_fusion(tokens=tokens, config=config, processor_output=processor_outputs)
    true_length += image_offsets

    if config.use_mrope:
      from maxtext.multimodal import processor_qwen3_omni  # pylint: disable=import-outside-toplevel

      position_ids, mrope_position_deltas = processor_qwen3_omni.get_rope_index(
          input_ids=tokens,
          image_grid_thw=processor_outputs.pixel_grid_thw,  # pytype: disable=attribute-error
          video_grid_thw=processor_outputs.video_grid_thw,  # pytype: disable=attribute-error
          attention_mask=np.ones_like(tokens),
          use_audio_in_video=config.use_audio and getattr(processor_outputs, 'num_videos', 0) > 0,
          audio_lengths=processor_outputs.audio_lengths,  # pytype: disable=attribute-error
          second_per_grids=processor_outputs.video_second_per_grid,  # pytype: disable=attribute-error
          spatial_merge_size=config.spatial_merge_size_for_vit,  # pytype: disable=attribute-error
          position_id_per_seconds=config.position_id_per_seconds,
      )

  assert (
      true_length <= config.max_prefill_predict_length
  ), f"Input token length {true_length} is longer than {config.max_prefill_predict_length=}"
  assert config.quantization != "fp8", "fp8 on NVIDIA GPUs is not supported in decode.py yet"
  assert config.quantization != "nanoo_fp8", "NANOO fp8 on AMD MI300/MI325 GPUs is not supported in decode.py yet"

  batch_size = int(config.per_device_batch_size * jax.device_count())
  assert (
      0 < _NUM_STREAMS <= batch_size
  ), f"The number of streams {_NUM_STREAMS} must be > 0 and <= batch size {batch_size}"

  prefill_result_list = []
  first_token_list = []
  sampled_tokens_list = []

  prof.activate(optional_postfix="trace")

  # Prefill
  _t_prefill = time.perf_counter()
  rng, rng_prefill = jax.random.split(rng)  # Split RNG before calling prefill
  for i in range(_NUM_STREAMS):
    with jax.profiler.StepTraceAnnotation("prefill", stream=i):
      if engine.use_chunked_prefill:
        chunk_size = engine.prefill_chunk_size
        n_chunks = config.max_prefill_predict_length // chunk_size
        rng_chunk = rng_prefill
        prefill_result = None
        first_token = None
        for chunk_idx in range(n_chunks):
          chunk_start = chunk_idx * chunk_size
          chunk_true_len = max(0, min(true_length - chunk_start, chunk_size))
          if chunk_true_len <= 0:
            break  # no more real tokens; leave remaining cache as zeros (masked)
          chunk_tokens = jnp.asarray(tokens[chunk_start : chunk_start + chunk_size])
          if chunk_idx == 0:
            prefill_result, first_token = engine.prefill(
                params=params,
                padded_tokens=chunk_tokens,
                true_length=chunk_true_len,
                rng=rng_chunk,
                slot=i,
            )
          else:
            existing_prefix = ExistingPrefix(
                cache=prefill_result["cache"],
                common_prefix_tokens=jnp.ones((chunk_idx * chunk_size,), dtype=jnp.int32),
            )
            rng_chunk, rng_pf = jax.random.split(rng_chunk)
            prefill_result, first_token = engine.prefill(
                params=params,
                existing_prefix=existing_prefix,
                padded_tokens=chunk_tokens,
                true_length=chunk_true_len,
                rng=rng_pf,
                slot=i,
            )
      else:
        prefill_result, first_token = engine.prefill(
            params=params,
            padded_tokens=tokens,
            positions=position_ids,
            mrope_deltas=mrope_position_deltas,
            images=processor_outputs.pixel_values if config.use_multimodal else None,
            image_masks=processor_outputs.pixel_mask if config.use_multimodal and "llama4" in config.model_name else None,
            audio_values=processor_outputs.audio_values if config.use_audio else None,
            audio_masks=processor_outputs.audio_mask if config.use_audio else None,
            true_length=true_length,
            rng=rng_prefill,
            slot=i,
        )
    prefill_result_list.append(prefill_result)
    first_token_list.append(first_token)
  _probe_hbm("after_prefill", detail=True)
  print(f"[TIME] prefill                           host={socket.gethostname()} elapsed={(time.perf_counter()-_t_prefill)*1000:.0f}ms", flush=True)

  # Insert
  rng, rng_init_decode = jax.random.split(rng)
  decode_state = engine.init_decode_state(rng_init_decode)
  for i in range(_NUM_STREAMS):
    decode_state = engine.insert(prefill_result_list[i], decode_state, slot=i)
  _probe_hbm("after_insert", detail=True)

  # Generate
  prof_deactivated = False
  steps = range(config.max_prefill_predict_length, config.max_target_length)
  sampled_tokens_list.append(_batch_first_result_token(first_token_list, batch_size))
  _t_gen_start = time.perf_counter()
  _eos_token_id = getattr(getattr(tokenizer_model, "tokenizer", None), "eos_token_id", None)
  for i in steps:
    rng, rng_generate = jax.random.split(rng)
    with jax.profiler.StepTraceAnnotation("generate", step=i):
      _t_step = time.perf_counter()
      decode_state, sampled_tokens = engine.generate(params, decode_state, rng=rng_generate)
      jax.effects_barrier()
      _step_ms = (time.perf_counter() - _t_step) * 1000
    print(f"[TIME] generate_step_{i:04d}              host={socket.gethostname()} step_ms={_step_ms:.1f}", flush=True)
    if i == steps[0] or (i - steps[0]) % 50 == 0:
      _probe_hbm(f"generate_step_{i:04d}", detail=(i == steps[0]))

    # Automatically deactivate profiler after profiler_steps steps
    if i > config.max_prefill_predict_length + config.profiler_steps:
      prof.deactivate(blocking_object=sampled_tokens)
      prof_deactivated = True

    sampled_tokens_list.append(sampled_tokens)

    # Early-stop when EOS is generated (slot 0, stream 0).
    if _eos_token_id is not None:
      _tok = sampled_tokens.get_result_at_slot(0).tokens.item()
      if _tok == _eos_token_id:
        print(f"[INFO] EOS token ({_eos_token_id}) generated at step {i}; stopping early.", flush=True)
        break

  _gen_total_s = time.perf_counter() - _t_gen_start
  print(
      f"[TIME] generate_total                    host={socket.gethostname()}"
      f" total={_gen_total_s:.1f}s steps={len(steps)}"
      f" avg_ms={_gen_total_s/len(steps)*1000:.1f}",
      flush=True,
  )

  # Get results
  for i in range(_NUM_STREAMS):
    results = [t.get_result_at_slot(i).tokens.item() for t in sampled_tokens_list]
    output = tokenizer_model.decode(results)
    print(f"Input `{text}` -> `{output}`")

  assert output.startswith(
      config.autoregressive_decode_assert
  ), f"generated text mismatch {output=}, {config.autoregressive_decode_assert=}"

  # Deactivate profiler
  if not prof_deactivated:
    prof.deactivate(blocking_object=output)

  prof.post_process()


def _validate_config(config):
  assert config.load_full_state_path == "", (
      "Decode doesn't operate on full states! Convert to parameter checkpoint first."
      "Using generate_param_only_checkpoint."
  )


if __name__ == "__main__":
  app.run(main)
